apiVersion: apps/v1
kind: Deployment
metadata:
  name: appweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appweb
  template:
    metadata:
      name: appweb
      labels:
        app: appweb
    spec:
      containers:
        - name: myapp
          image: fabricioveronez/web-page:green
         # resources:
          #  limits:
           #   memory: "50Mi"
           #   cpu: "10m"
          ports:
            - containerPort: 80
